export const Users = [
  {
    name: "Susan Savage",
    DateOfEmployment: "2024-01-30",
    department: "Engineering",
    role: "Database Administrator",
    email: "susan.savage@techpack.mn",
  },
  {
    name: "Tara Nelson",
    DateOfEmployment: "2021-05-22",
    department: "Sales",
    role: "Merchandiser, Retail",
    email: "tara.nelson@techpack.mn",
  },
  {
    name: "Michael Johnson",
    DateOfEmployment: "2019-03-14",
    department: "Finance",
    role: "Accountant",
    email: "michael.johnson@techpack.mn",
  },
  {
    name: "Emily Carter",
    DateOfEmployment: "2022-07-10",
    department: "HR",
    role: "Recruiter",
    email: "emily.carter@techpack.mn",
  },
  {
    name: "David Thompson",
    DateOfEmployment: "2020-09-01",
    department: "Engineering",
    role: "Frontend Developer",
    email: "david.thompson@techpack.mn",
  },
  {
    name: "Sophia Martinez",
    DateOfEmployment: "2018-12-11",
    department: "Engineering",
    role: "Backend Developer",
    email: "sophia.martinez@techpack.mn",
  },
  {
    name: "James Anderson",
    DateOfEmployment: "2023-02-19",
    department: "Sales",
    role: "Sales Executive",
    email: "james.anderson@techpack.mn",
  },
  {
    name: "Olivia Brown",
    DateOfEmployment: "2020-06-25",
    department: "Finance",
    role: "Financial Analyst",
    email: "olivia.brown@techpack.mn",
  },
  {
    name: "Daniel White",
    DateOfEmployment: "2021-10-09",
    department: "HR",
    role: "HR Manager",
    email: "daniel.white@techpack.mn",
  },
  {
    name: "Isabella Garcia",
    DateOfEmployment: "2019-04-15",
    department: "Engineering",
    role: "DevOps Engineer",
    email: "isabella.garcia@techpack.mn",
  },
  {
    name: "Matthew Harris",
    DateOfEmployment: "2022-11-03",
    department: "Design",
    role: "UI/UX Designer",
    email: "matthew.harris@techpack.mn",
  },
  {
    name: "Ava Wilson",
    DateOfEmployment: "2017-08-28",
    department: "Sales",
    role: "Sales Manager",
    email: "ava.wilson@techpack.mn",
  },
  {
    name: "William Robinson",
    DateOfEmployment: "2020-01-05",
    department: "Engineering",
    role: "Mobile Developer",
    email: "william.robinson@techpack.mn",
  },
  {
    name: "Mia Clark",
    DateOfEmployment: "2021-12-12",
    department: "Finance",
    role: "Payroll Specialist",
    email: "mia.clark@techpack.mn",
  },
  {
    name: "Ethan Lewis",
    DateOfEmployment: "2018-02-17",
    department: "Engineering",
    role: "Fullstack Developer",
    email: "ethan.lewis@techpack.mn",
  },
  {
    name: "Charlotte Young",
    DateOfEmployment: "2023-06-01",
    department: "HR",
    role: "Talent Acquisition",
    email: "charlotte.young@techpack.mn",
  },
  {
    name: "Henry King",
    DateOfEmployment: "2022-04-07",
    department: "Engineering",
    role: "QA Engineer",
    email: "henry.king@techpack.mn",
  },
  {
    name: "Amelia Scott",
    DateOfEmployment: "2019-09-21",
    department: "Design",
    role: "Graphic Designer",
    email: "amelia.scott@techpack.mn",
  },
  {
    name: "Alexander Green",
    DateOfEmployment: "2021-01-18",
    department: "Engineering",
    role: "System Administrator",
    email: "alexander.green@techpack.mn",
  },
  {
    name: "Harper Adams",
    DateOfEmployment: "2017-05-27",
    department: "Sales",
    role: "Account Manager",
    email: "harper.adams@techpack.mn",
  },
  {
    name: "Tara Leonard",
    DateOfEmployment: "2018-03-16",
    department: "Marketing",
    role: "Content Strategist",
    email: "tara.leonard@techpack.mn",
  },
  {
    name: "Amy Rose",
    DateOfEmployment: "2019-10-17",
    department: "Sales",
    role: "Account Manager",
    email: "amy.rose@techpack.mn",
  },
  {
    name: "John Welch",
    DateOfEmployment: "2022-12-12",
    department: "Finance",
    role: "Payroll Specialist",
    email: "john.welch@techpack.mn",
  },
  {
    name: "Dennis Ward",
    DateOfEmployment: "2023-12-24",
    department: "Sales",
    role: "Merchandiser, Retail",
    email: "dennis.ward@techpack.mn",
  },
  {
    name: "Eric Ballard",
    DateOfEmployment: "2018-09-09",
    department: "Marketing",
    role: "Content Strategist",
    email: "eric.ballard@techpack.mn",
  },
  {
    name: "Jeffrey Pugh",
    DateOfEmployment: "2024-10-07",
    department: "HR",
    role: "Recruiter",
    email: "jeffrey.pugh@techpack.mn",
  },
  {
    name: "Amy Bolton",
    DateOfEmployment: "2020-08-20",
    department: "Support",
    role: "Helpdesk Specialist",
    email: "amy.bolton@techpack.mn",
  },
  {
    name: "Brianna Davis",
    DateOfEmployment: "2021-02-23",
    department: "Engineering",
    role: "QA Engineer",
    email: "brianna.davis@techpack.mn",
  },
  {
    name: "Virginia Kelley",
    DateOfEmployment: "2024-08-15",
    department: "Design",
    role: "UI/UX Designer",
    email: "virginia.kelley@techpack.mn",
  },
  {
    name: "Allen Schneider",
    DateOfEmployment: "2018-07-05",
    department: "HR",
    role: "Talent Acquisition",
    email: "allen.schneider@techpack.mn",
  },
  {
    name: "James Robinson",
    DateOfEmployment: "2017-09-16",
    department: "Marketing",
    role: "SEO Manager",
    email: "james.robinson@techpack.mn",
  },
  {
    name: "William Martinez",
    DateOfEmployment: "2021-08-09",
    department: "HR",
    role: "Talent Acquisition",
    email: "william.martinez@techpack.mn",
  },
  {
    name: "Krista Mitchell",
    DateOfEmployment: "2023-12-23",
    department: "Sales",
    role: "Merchandiser, Retail",
    email: "krista.mitchell@techpack.mn",
  },
  {
    name: "Christopher Martinez",
    DateOfEmployment: "2018-01-22",
    department: "Marketing",
    role: "Content Strategist",
    email: "christopher.martinez@techpack.mn",
  },
  {
    name: "Derrick Green",
    DateOfEmployment: "2024-01-27",
    department: "Support",
    role: "Helpdesk Specialist",
    email: "derrick.green@techpack.mn",
  },
  {
    name: "Melissa Mullins",
    DateOfEmployment: "2021-05-14",
    department: "Marketing",
    role: "Marketing Specialist",
    email: "melissa.mullins@techpack.mn",
  },
  {
    name: "Sarah Barber",
    DateOfEmployment: "2019-05-27",
    department: "Marketing",
    role: "Content Strategist",
    email: "sarah.barber@techpack.mn",
  },
  {
    name: "Thomas Gonzales",
    DateOfEmployment: "2019-04-29",
    department: "Design",
    role: "Product Designer",
    email: "thomas.gonzales@techpack.mn",
  },
  {
    name: "Debra Powell",
    DateOfEmployment: "2015-10-20",
    department: "HR",
    role: "Talent Acquisition",
    email: "debra.powell@techpack.mn",
  },
  {
    name: "Nicole Arnold",
    DateOfEmployment: "2022-03-31",
    department: "Support",
    role: "Helpdesk Specialist",
    email: "nicole.arnold@techpack.mn",
  },
  {
    name: "Eric Hernandez",
    DateOfEmployment: "2018-11-28",
    department: "Finance",
    role: "Accountant",
    email: "eric.hernandez@techpack.mn",
  },
  {
    name: "Robert Bass",
    DateOfEmployment: "2024-08-27",
    department: "Design",
    role: "Graphic Designer",
    email: "robert.bass@techpack.mn",
  },
  {
    name: "Rebecca Lopez",
    DateOfEmployment: "2023-04-26",
    department: "Design",
    role: "UI/UX Designer",
    email: "rebecca.lopez@techpack.mn",
  },
  {
    name: "Tyler Murray",
    DateOfEmployment: "2019-11-03",
    department: "HR",
    role: "Recruiter",
    email: "tyler.murray@techpack.mn",
  },
  {
    name: "B.Battulga",
    DateOfEmployment: "2025-08-29",
    department: "Design , Machine Learning , Artificial Intelligence",
    role: "UI/UX Designer , Software Engineer ,Data Analyst",
    email: "tuka@techpack.mn",
  },
  {
    name: "Jennifer Gallegos",
    DateOfEmployment: "2023-10-25",
    department: "Design",
    role: "UI/UX Designer",
    email: "jennifer.gallegos@techpack.mn",
  },
  {
    name: "Kelly Jackson",
    DateOfEmployment: "2019-03-30",
    department: "HR",
    role: "Recruiter",
    email: "kelly.jackson@techpack.mn",
  },
  {
    name: "Rebecca Palmer",
    DateOfEmployment: "2020-11-04",
    department: "Engineering",
    role: "DevOps Engineer",
    email: "rebecca.palmer@techpack.mn",
  },
  {
    name: "Devin Raymond",
    DateOfEmployment: "2021-02-20",
    department: "Sales",
    role: "Sales Manager",
    email: "devin.raymond@techpack.mn",
  },
  {
    name: "Dana Becker",
    DateOfEmployment: "2020-08-16",
    department: "Engineering",
    role: "Mobile Developer",
    email: "dana.becker@techpack.mn",
  },
  {
    name: "Anthony Snyder",
    DateOfEmployment: "2018-02-14",
    department: "Engineering",
    role: "Mobile Developer",
    email: "anthony.snyder@techpack.mn",
  },
  {
    name: "Timothy Garcia",
    DateOfEmployment: "2021-07-28",
    department: "Support",
    role: "Helpdesk Specialist",
    email: "timothy.garcia@techpack.mn",
  },
  {
    name: "Beth Newman",
    DateOfEmployment: "2021-06-21",
    department: "Marketing",
    role: "SEO Manager",
    email: "beth.newman@techpack.mn",
  },
  {
    name: "Robert Page",
    DateOfEmployment: "2023-11-05",
    department: "Design",
    role: "UI/UX Designer",
    email: "robert.page@techpack.mn",
  },
  {
    name: "Levi Martinez",
    DateOfEmployment: "2015-12-17",
    department: "Finance",
    role: "Accountant",
    email: "levi.martinez@techpack.mn",
  },
  {
    name: "Lori Peterson",
    DateOfEmployment: "2021-07-07",
    department: "Support",
    role: "Technical Support",
    email: "lori.peterson@techpack.mn",
  },
  {
    name: "Brandon Perkins",
    DateOfEmployment: "2023-03-09",
    department: "Marketing",
    role: "Content Strategist",
    email: "brandon.perkins@techpack.mn",
  },
  {
    name: "Zachary Holmes",
    DateOfEmployment: "2019-02-03",
    department: "Finance",
    role: "Financial Analyst",
    email: "zachary.holmes@techpack.mn",
  },
  {
    name: "Matthew Fernandez",
    DateOfEmployment: "2020-07-22",
    department: "Sales",
    role: "Merchandiser, Retail",
    email: "matthew.fernandez@techpack.mn",
  },
  {
    name: "Oscar Jones",
    DateOfEmployment: "2024-02-23",
    department: "Sales",
    role: "Account Manager",
    email: "oscar.jones@techpack.mn",
  },
  {
    name: "Billy Mitchell",
    DateOfEmployment: "2023-03-26",
    department: "Marketing",
    role: "SEO Manager",
    email: "billy.mitchell@techpack.mn",
  },
  {
    name: "Luke Phillips",
    DateOfEmployment: "2016-10-27",
    department: "Marketing",
    role: "SEO Manager",
    email: "luke.phillips@techpack.mn",
  },
  {
    name: "Kenneth Allen",
    DateOfEmployment: "2019-05-16",
    department: "Design",
    role: "UI/UX Designer",
    email: "kenneth.allen@techpack.mn",
  },
  {
    name: "Christina Rodriguez",
    DateOfEmployment: "2023-06-01",
    department: "Support",
    role: "Customer Support",
    email: "christina.rodriguez@techpack.mn",
  },
  {
    name: "Mr. Roger Powell",
    DateOfEmployment: "2022-06-15",
    department: "Sales",
    role: "Sales Executive",
    email: "mr..roger.powell@techpack.mn",
  },
  {
    name: "Douglas Walsh",
    DateOfEmployment: "2016-09-25",
    department: "Support",
    role: "Technical Support",
    email: "douglas.walsh@techpack.mn",
  },
  {
    name: "Amanda Castaneda",
    DateOfEmployment: "2021-06-30",
    department: "Sales",
    role: "Account Manager",
    email: "amanda.castaneda@techpack.mn",
  },
  {
    name: "Trevor Wilson",
    DateOfEmployment: "2019-12-22",
    department: "Support",
    role: "Customer Support",
    email: "trevor.wilson@techpack.mn",
  },
  {
    name: "Marie Bell DVM",
    DateOfEmployment: "2018-05-18",
    department: "Design",
    role: "UI/UX Designer",
    email: "marie.bell.dvm@techpack.mn",
  },
  {
    name: "Mathew Carter",
    DateOfEmployment: "2018-05-04",
    department: "Engineering",
    role: "DevOps Engineer",
    email: "mathew.carter@techpack.mn",
  },
  {
    name: "Mary Hill",
    DateOfEmployment: "2016-11-25",
    department: "HR",
    role: "HR Manager",
    email: "mary.hill@techpack.mn",
  },
  {
    name: "Nathan Knight",
    DateOfEmployment: "2021-02-07",
    department: "Support",
    role: "Helpdesk Specialist",
    email: "nathan.knight@techpack.mn",
  },
  {
    name: "Donna Owen",
    DateOfEmployment: "2021-12-03",
    department: "Design",
    role: "Product Designer",
    email: "donna.owen@techpack.mn",
  },
  {
    name: "Joseph Peters",
    DateOfEmployment: "2022-09-01",
    department: "Engineering",
    role: "System Administrator",
    email: "joseph.peters@techpack.mn",
  },
  {
    name: "Jennifer Howell",
    DateOfEmployment: "2021-06-28",
    department: "Finance",
    role: "Auditor",
    email: "jennifer.howell@techpack.mn",
  },
  {
    name: "Dustin Hughes",
    DateOfEmployment: "2024-03-07",
    department: "Engineering",
    role: "Frontend Developer",
    email: "dustin.hughes@techpack.mn",
  },
  {
    name: "Clinton Carr",
    DateOfEmployment: "2020-07-29",
    department: "Design",
    role: "Graphic Designer",
    email: "clinton.carr@techpack.mn",
  },
  {
    name: "Sharon Weaver",
    DateOfEmployment: "2016-03-08",
    department: "Support",
    role: "Helpdesk Specialist",
    email: "sharon.weaver@techpack.mn",
  },
  {
    name: "Jessica Meza",
    DateOfEmployment: "2015-08-30",
    department: "Sales",
    role: "Sales Executive",
    email: "jessica.meza@techpack.mn",
  },
  {
    name: "Alexandria Taylor",
    DateOfEmployment: "2019-02-03",
    department: "Finance",
    role: "Financial Analyst",
    email: "alexandria.taylor@techpack.mn",
  },
  {
    name: "Michael Roberts",
    DateOfEmployment: "2019-07-25",
    department: "Marketing",
    role: "Marketing Specialist",
    email: "michael.roberts@techpack.mn",
  },
  {
    name: "Deborah Young",
    DateOfEmployment: "2017-08-21",
    department: "Engineering",
    role: "Frontend Developer",
    email: "deborah.young@techpack.mn",
  },
  {
    name: "Cindy Young",
    DateOfEmployment: "2024-05-04",
    department: "Finance",
    role: "Financial Analyst",
    email: "cindy.young@techpack.mn",
  },
  {
    name: "Megan Gibbs",
    DateOfEmployment: "2019-12-15",
    department: "Design",
    role: "UI/UX Designer",
    email: "megan.gibbs@techpack.mn",
  },
  {
    name: "Dwayne Khan",
    DateOfEmployment: "2024-11-05",
    department: "Engineering",
    role: "DevOps Engineer",
    email: "dwayne.khan@techpack.mn",
  },
  {
    name: "Brandon Tran",
    DateOfEmployment: "2023-07-10",
    department: "Sales",
    role: "Sales Manager",
    email: "brandon.tran@techpack.mn",
  },
  {
    name: "Michelle Acosta",
    DateOfEmployment: "2020-11-08",
    department: "Support",
    role: "Customer Support",
    email: "michelle.acosta@techpack.mn",
  },
  {
    name: "Gina Drake",
    DateOfEmployment: "2023-03-02",
    department: "Sales",
    role: "Account Manager",
    email: "gina.drake@techpack.mn",
  },
  {
    name: "Lisa Garrett",
    DateOfEmployment: "2017-06-01",
    department: "Sales",
    role: "Merchandiser, Retail",
    email: "lisa.garrett@techpack.mn",
  },
  {
    name: "Tyler Bradshaw",
    DateOfEmployment: "2017-06-30",
    department: "Engineering",
    role: "Mobile Developer",
    email: "tyler.bradshaw@techpack.mn",
  },
  {
    name: "Maria Randolph",
    DateOfEmployment: "2023-07-20",
    department: "Finance",
    role: "Accountant",
    email: "maria.randolph@techpack.mn",
  },
  {
    name: "Diane Velasquez",
    DateOfEmployment: "2017-10-06",
    department: "Engineering",
    role: "Mobile Developer",
    email: "diane.velasquez@techpack.mn",
  },
  {
    name: "Eric Davis",
    DateOfEmployment: "2015-09-08",
    department: "Design",
    role: "UI/UX Designer",
    email: "eric.davis@techpack.mn",
  },
  {
    name: "Rodney Harris",
    DateOfEmployment: "2018-03-26",
    department: "Sales",
    role: "Sales Executive",
    email: "rodney.harris@techpack.mn",
  },
  {
    name: "Paul Howard",
    DateOfEmployment: "2022-03-24",
    department: "Sales",
    role: "Sales Manager",
    email: "paul.howard@techpack.mn",
  },
  {
    name: "Tracy Boyd",
    DateOfEmployment: "2018-04-23",
    department: "Design",
    role: "Graphic Designer",
    email: "tracy.boyd@techpack.mn",
  },
  {
    name: "John Mason",
    DateOfEmployment: "2019-11-14",
    department: "Marketing",
    role: "Content Strategist",
    email: "john.mason@techpack.mn",
  },
  {
    name: "William Salinas",
    DateOfEmployment: "2018-06-11",
    department: "Finance",
    role: "Accountant",
    email: "william.salinas@techpack.mn",
  },
  {
    name: "Amy Navarro",
    DateOfEmployment: "2015-09-04",
    department: "Engineering",
    role: "System Administrator",
    email: "amy.navarro@techpack.mn",
  },
  {
    name: "Kevin George",
    DateOfEmployment: "2019-12-04",
    department: "Design",
    role: "Graphic Designer",
    email: "kevin.george@techpack.mn",
  },
];
